apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbit.fullname" . }}
  labels:
    {{- include "orbit.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "orbit.selectorLabels" . | nindent 4 }}
    component: node
  ports:
  - name: grpc
    port: {{ .Values.node.containerPort }}
