apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbit.fullname" . }}
  labels:
    {{- include "orbit.selectorLabels" . | nindent 4 }}
  {{- if .Values.node.service.annotations }}
  annotations:
    {{- toYaml .Values.node.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "orbit.selectorLabels" . | nindent 4 }}
    component: node
  ports:
  - name: grpc
    port: {{ .Values.node.containerPort }}
  - name: metrics
    port:  {{ .Values.node.metricsPort }}
