version: "3.7"
services:
  orbit-server-1:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - "5006:5005"
    expose:
      - 50056
    environment:
      ORBIT_SETTINGS: /etc/orbit/orbit.json
      ORBIT_URL: "orbit-server-1:50056"
      ORBIT_PORT: 50056
      ETCD_ADDRESSABLE_DIR: http://node-directory:2379
      ETCD_NODE_DIR: http://addressable-directory:2379
    entrypoint: sh ./opt/orbit/entrypoint.sh
    volumes:
      - ../src/orbit-application/build/libs:/opt/orbit/libs
      - ./local-compose-orbit-settings.json:/etc/orbit/orbit.json
  orbit-server-2:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - "5007:5005"
    expose:
      - 50056
    environment:
      ORBIT_SETTINGS: /etc/orbit/orbit.json
      ORBIT_URL: "orbit-server-2:50056"
      ORBIT_PORT: 50056
      ETCD_ADDRESSABLE_DIR: http://node-directory:2379
      ETCD_NODE_DIR: http://addressable-directory:2379
    entrypoint: sh -c ./opt/orbit/entrypoint.sh
    volumes:
      - ../src/orbit-application/build/libs:/opt/orbit/libs
      - ./local-compose-orbit-settings.json:/etc/orbit/orbit.json
  node-directory:
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-server:2379
    expose:
      - 2379
      - 2380
  addressable-directory:
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-server:2379
    expose:
      - 2379
      - 2380
  mesh-proxy:
    image: haproxy:2.0-alpine
    container_name: mesh-proxy
    depends_on:
      - orbit-server-1
      - orbit-server-2
    ports:
      - "50056:50056"
    expose:
      - 50056
    volumes:
      - ./proxy/config:/usr/local/etc/haproxy:rw
    restart: always
