# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

url: localhost

node:
  image:
    repository: orbitframework/orbit
    tag: 2.0.0-alpha.46
    pullPolicy: IfNotPresent
  replicas: 1
  containerPort: 50056
  metricsPort: 8080

addressableDirectory:
  image:
    repository: bitnami/etcd
    tag: "3"
    pullPolicy: IfNotPresent
  replicas: 0
  clientPort: 2379
  peerPort: 2380

nodeDirectory:
  image:
    repository: bitnami/etcd
    tag: "3"
    pullPolicy: IfNotPresent
  replicas: 0
  clientPort: 2379
  peerPort: 2380

