name: Build Orbit

on: [push, pull_request]

jobs:
  build:
    name: Build on JDK ${{ matrix.jdk }}
    strategy:
      matrix:
        jdk: [ '8', '11', '13' ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Build with Gradle
        run: ./gradlew build
