name: Helm

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Announce
      run: echo Releasing helm chart
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.0.0-alpha.2
      with:
        charts_dir: /deploy/helm
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
